# Site Info
title:              "Lucas Paulger"
description:        "Web Developer"
#google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-23249160-1 # Put your Google Analytics code

# Author Info
author_name:        "Lucas Paulger"
author_email:       lucas.paulger@gmail.com
author_gravatar:    64fa194d80712ca6caa1843bc538a11e # Gravatar md5 hash
twitter_username:   lmpaulger
github_username:    lpaulger
medium_username:    lpaulger

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:categories/:year/:month/:day/:title/  # Post permalink
timezone:           Europe/Bucharest # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  # comments :
  #   provider : disqus
  #   disqus :
  #     short_name : lpprojects

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
